version: '3'
services:
  es01:
    build: ./
    image: own_elasticsearch:${OWN_ES_VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/data01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - elastic
  es02:
    build: ./
    image: own_elasticsearch:${OWN_ES_VERSION}
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  # es03:
  #   build: ./
  #   image: own_elasticsearch:${OWN_ES_VERSION}
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=${CLUSTER_NAME}
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./data/data03:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    networks:
      - elastic
  logstash:
    depends_on:
      - es01
      - es02
      # - es03
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./data/logstash:/mnt
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://es01:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - elastic
  cerebro:
    image: lmenezes/cerebro:0.8.3
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://es01:9200
    networks:
     - elastic

networks:
  elastic:
    driver: bridge
