version: "3"
services:
  es_01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
      - node.name=es_01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es_02,es_03
      - cluster.initial_master_nodes=es_01,es_02,es_03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/data01:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elastic
  es_02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
      - node.name=es_02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es_01,es_03
      - cluster.initial_master_nodes=es_01,es_02,es_03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/data02:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
  es_03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
      - node.name=es_03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es_01,es_02
      - cluster.initial_master_nodes=es_01,es_02,es_03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/data03:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    ports: 
      - 5601:5601
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

  
networks:
  elastic:
    driver: bridge
