version: "3"
services:
  es:
    images: elasticsearch:8.2.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      elastic: {}
networks:
  elastic:
    driver: bridge
